# The tarballs in vendor/ again, for pnpm.
#
# Written by scripts/vendor-gesso.sh. pnpm 11 reads overrides only
# from this file, not from package.json.
overrides:
  gesso-components: file:vendor/gesso-components-0.2.1-af57cdae.tgz
  gesso-core: file:vendor/gesso-core-0.2.1-1b7813d8.tgz
  gesso-devtools: file:vendor/gesso-devtools-0.2.1-463f467f.tgz
  gesso-framework: file:vendor/gesso-framework-0.2.1-a04abb57.tgz
  gesso-testing: file:vendor/gesso-testing-0.2.1-38196b17.tgz
  gesso-vite-plugin: file:vendor/gesso-vite-plugin-0.2.1-19701287.tgz
