/**
 * Heroicons, as path data.
 *
 * Generated by `pnpm icons` from heroicons@2.2.0. Do not edit:
 * `scripts/icons.ts` holds the list of glyphs and rewrites this file.
 *
 * Heroicons is MIT licensed — Copyright (c) Tailwind Labs, Inc. The
 * licence is at `node_modules/heroicons/LICENSE` and travels with
 * this data.
 */
import type { Glyph } from './icons';

/** Heroicons `arrow-path`, 24×24 outline. */
export const arrowPath: Glyph = {
  path:
    'M16.023 9.348h4.992v-.001M2.985 19.644v-4.992m0 0h4.992m-4.993 0 3.181 3.183a8.25 8.25 0 0 0 13.803-3.7M4.031 9.865a8.25 8.25 0 0 1 13.803-3.7l3.181 3.182m0-4.991v4.99',
  viewBox: 24,
  style: 'stroke',
  strokeWidth: 1.5
};

/** Heroicons `arrow-uturn-left`, 24×24 outline. */
export const arrowUturnLeft: Glyph = {
  path: 'M9 15 3 9m0 0 6-6M3 9h12a6 6 0 0 1 0 12h-3',
  viewBox: 24,
  style: 'stroke',
  strokeWidth: 1.5
};

/** Heroicons `arrow-uturn-right`, 24×24 outline. */
export const arrowUturnRight: Glyph = {
  path: 'm15 15 6-6m0 0-6-6m6 6H9a6 6 0 0 0 0 12h3',
  viewBox: 24,
  style: 'stroke',
  strokeWidth: 1.5
};

/** Heroicons `bars-3-bottom-left`, 24×24 outline. */
export const bars3BottomLeft: Glyph = {
  path: 'M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25H12',
  viewBox: 24,
  style: 'stroke',
  strokeWidth: 1.5
};

/** Heroicons `bars-3-bottom-right`, 24×24 outline. */
export const bars3BottomRight: Glyph = {
  path: 'M3.75 6.75h16.5M3.75 12h16.5M12 17.25h8.25',
  viewBox: 24,
  style: 'stroke',
  strokeWidth: 1.5
};

/** Heroicons `bold`, 24×24 outline. */
export const bold: Glyph = {
  path:
    'M6.75 3.744h-.753v8.25h7.125a4.125 4.125 0 0 0 0-8.25H6.75Zm0 0v.38m0 16.122h6.747a4.5 4.5 0 0 0 0-9.001h-7.5v9h.753Zm0 0v-.37m0-15.751h6a3.75 3.75 0 1 1 0 7.5h-6m0-7.5v7.5m0 0v8.25m0-8.25h6.375a4.125 4.125 0 0 1 0 8.25H6.75m.747-15.38h4.875a3.375 3.375 0 0 1 0 6.75H7.497v-6.75Zm0 7.5h5.25a3.75 3.75 0 0 1 0 7.5h-5.25v-7.5Z',
  viewBox: 24,
  style: 'stroke',
  strokeWidth: 1.5
};

/** Heroicons `currency-dollar`, 24×24 outline. */
export const currencyDollar: Glyph = {
  path:
    'M12 6v12m-3-2.818.879.659c1.171.879 3.07.879 4.242 0 1.172-.879 1.172-2.303 0-3.182C13.536 12.219 12.768 12 12 12c-.725 0-1.45-.22-2.003-.659-1.106-.879-1.106-2.303 0-3.182s2.9-.879 4.006 0l.415.33M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z',
  viewBox: 24,
  style: 'stroke',
  strokeWidth: 1.5
};

/** Heroicons `italic`, 24×24 outline. */
export const italic: Glyph = {
  path:
    'M5.248 20.246H9.05m0 0h3.696m-3.696 0 5.893-16.502m0 0h-3.697m3.697 0h3.803',
  viewBox: 24,
  style: 'stroke',
  strokeWidth: 1.5
};

/** Heroicons `percent-badge`, 24×24 outline. */
export const percentBadge: Glyph = {
  path:
    'm8.99 14.993 6-6m6 3.001c0 1.268-.63 2.39-1.593 3.069a3.746 3.746 0 0 1-1.043 3.296 3.745 3.745 0 0 1-3.296 1.043 3.745 3.745 0 0 1-3.068 1.593c-1.268 0-2.39-.63-3.068-1.593a3.745 3.745 0 0 1-3.296-1.043 3.746 3.746 0 0 1-1.043-3.297 3.746 3.746 0 0 1-1.593-3.068c0-1.268.63-2.39 1.593-3.068a3.746 3.746 0 0 1 1.043-3.297 3.745 3.745 0 0 1 3.296-1.042 3.745 3.745 0 0 1 3.068-1.594c1.268 0 2.39.63 3.068 1.593a3.745 3.745 0 0 1 3.296 1.043 3.746 3.746 0 0 1 1.043 3.297 3.746 3.746 0 0 1 1.593 3.068ZM9.74 9.743h.008v.007H9.74v-.007Zm.375 0a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Zm4.125 4.5h.008v.008h-.008v-.008Zm.375 0a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Z',
  viewBox: 24,
  style: 'stroke',
  strokeWidth: 1.5
};

/** Heroicons `underline`, 24×24 outline. */
export const underline: Glyph = {
  path: 'M17.995 3.744v7.5a6 6 0 1 1-12 0v-7.5m-2.25 16.502h16.5',
  viewBox: 24,
  style: 'stroke',
  strokeWidth: 1.5
};
