/**
 * Heroicons, as path data.
 *
 * Generated by `pnpm icons` from heroicons@2.2.0. Do not edit:
 * `scripts/icons.ts` holds the list of glyphs and rewrites this file.
 *
 * Heroicons is MIT licensed — Copyright (c) Tailwind Labs, Inc. The
 * licence is at `node_modules/heroicons/LICENSE` and travels with
 * this data.
 */
import type { Glyph } from './icons';

/** Heroicons `arrow-path`, 24×24 outline. */
export const arrowPath: Glyph = {
  path:
    'M16.023 9.348h4.992v-.001M2.985 19.644v-4.992m0 0h4.992m-4.993 0 3.181 3.183a8.25 8.25 0 0 0 13.803-3.7M4.031 9.865a8.25 8.25 0 0 1 13.803-3.7l3.181 3.182m0-4.991v4.99',
  viewBox: 24,
  style: 'stroke',
  strokeWidth: 1.5
};

/** Heroicons `arrow-uturn-left`, 24×24 outline. */
export const arrowUturnLeft: Glyph = {
  path: 'M9 15 3 9m0 0 6-6M3 9h12a6 6 0 0 1 0 12h-3',
  viewBox: 24,
  style: 'stroke',
  strokeWidth: 1.5
};

/** Heroicons `arrow-uturn-right`, 24×24 outline. */
export const arrowUturnRight: Glyph = {
  path: 'm15 15 6-6m0 0-6-6m6 6H9a6 6 0 0 0 0 12h3',
  viewBox: 24,
  style: 'stroke',
  strokeWidth: 1.5
};

/** Heroicons `bars-3-bottom-left`, 24×24 outline. */
export const bars3BottomLeft: Glyph = {
  path: 'M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25H12',
  viewBox: 24,
  style: 'stroke',
  strokeWidth: 1.5
};

/** Heroicons `bars-3-bottom-right`, 24×24 outline. */
export const bars3BottomRight: Glyph = {
  path: 'M3.75 6.75h16.5M3.75 12h16.5M12 17.25h8.25',
  viewBox: 24,
  style: 'stroke',
  strokeWidth: 1.5
};

/** Heroicons `bold`, 24×24 outline. */
export const bold: Glyph = {
  path:
    'M6.75 3.744h-.753v8.25h7.125a4.125 4.125 0 0 0 0-8.25H6.75Zm0 0v.38m0 16.122h6.747a4.5 4.5 0 0 0 0-9.001h-7.5v9h.753Zm0 0v-.37m0-15.751h6a3.75 3.75 0 1 1 0 7.5h-6m0-7.5v7.5m0 0v8.25m0-8.25h6.375a4.125 4.125 0 0 1 0 8.25H6.75m.747-15.38h4.875a3.375 3.375 0 0 1 0 6.75H7.497v-6.75Zm0 7.5h5.25a3.75 3.75 0 0 1 0 7.5h-5.25v-7.5Z',
  viewBox: 24,
  style: 'stroke',
  strokeWidth: 1.5
};

/** Heroicons `clock`, 24×24 outline. */
export const clock: Glyph = {
  path: 'M12 6v6h4.5m4.5 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z',
  viewBox: 24,
  style: 'stroke',
  strokeWidth: 1.5
};

/** Heroicons `currency-dollar`, 24×24 outline. */
export const currencyDollar: Glyph = {
  path:
    'M12 6v12m-3-2.818.879.659c1.171.879 3.07.879 4.242 0 1.172-.879 1.172-2.303 0-3.182C13.536 12.219 12.768 12 12 12c-.725 0-1.45-.22-2.003-.659-1.106-.879-1.106-2.303 0-3.182s2.9-.879 4.006 0l.415.33M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z',
  viewBox: 24,
  style: 'stroke',
  strokeWidth: 1.5
};

/** Heroicons `funnel`, 24×24 outline. */
export const funnel: Glyph = {
  path:
    'M12 3c2.755 0 5.455.232 8.083.678.533.09.917.556.917 1.096v1.044a2.25 2.25 0 0 1-.659 1.591l-5.432 5.432a2.25 2.25 0 0 0-.659 1.591v2.927a2.25 2.25 0 0 1-1.244 2.013L9.75 21v-6.568a2.25 2.25 0 0 0-.659-1.591L3.659 7.409A2.25 2.25 0 0 1 3 5.818V4.774c0-.54.384-1.006.917-1.096A48.32 48.32 0 0 1 12 3Z',
  viewBox: 24,
  style: 'stroke',
  strokeWidth: 1.5
};

/** Heroicons `italic`, 24×24 outline. */
export const italic: Glyph = {
  path:
    'M5.248 20.246H9.05m0 0h3.696m-3.696 0 5.893-16.502m0 0h-3.697m3.697 0h3.803',
  viewBox: 24,
  style: 'stroke',
  strokeWidth: 1.5
};

/** Heroicons `paint-brush`, 24×24 outline. */
export const paintBrush: Glyph = {
  path:
    'M9.53 16.122a3 3 0 0 0-5.78 1.128 2.25 2.25 0 0 1-2.4 2.245 4.5 4.5 0 0 0 8.4-2.245c0-.399-.078-.78-.22-1.128Zm0 0a15.998 15.998 0 0 0 3.388-1.62m-5.043-.025a15.994 15.994 0 0 1 1.622-3.395m3.42 3.42a15.995 15.995 0 0 0 4.764-4.648l3.876-5.814a1.151 1.151 0 0 0-1.597-1.597L14.146 6.32a15.996 15.996 0 0 0-4.649 4.763m3.42 3.42a6.776 6.776 0 0 0-3.42-3.42',
  viewBox: 24,
  style: 'stroke',
  strokeWidth: 1.5
};

/** Heroicons `percent-badge`, 24×24 outline. */
export const percentBadge: Glyph = {
  path:
    'm8.99 14.993 6-6m6 3.001c0 1.268-.63 2.39-1.593 3.069a3.746 3.746 0 0 1-1.043 3.296 3.745 3.745 0 0 1-3.296 1.043 3.745 3.745 0 0 1-3.068 1.593c-1.268 0-2.39-.63-3.068-1.593a3.745 3.745 0 0 1-3.296-1.043 3.746 3.746 0 0 1-1.043-3.297 3.746 3.746 0 0 1-1.593-3.068c0-1.268.63-2.39 1.593-3.068a3.746 3.746 0 0 1 1.043-3.297 3.745 3.745 0 0 1 3.296-1.042 3.745 3.745 0 0 1 3.068-1.594c1.268 0 2.39.63 3.068 1.593a3.745 3.745 0 0 1 3.296 1.043 3.746 3.746 0 0 1 1.043 3.297 3.746 3.746 0 0 1 1.593 3.068ZM9.74 9.743h.008v.007H9.74v-.007Zm.375 0a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Zm4.125 4.5h.008v.008h-.008v-.008Zm.375 0a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Z',
  viewBox: 24,
  style: 'stroke',
  strokeWidth: 1.5
};

/** Heroicons `printer`, 24×24 outline. */
export const printer: Glyph = {
  path:
    'M6.72 13.829c-.24.03-.48.062-.72.096m.72-.096a42.415 42.415 0 0 1 10.56 0m-10.56 0L6.34 18m10.94-4.171c.24.03.48.062.72.096m-.72-.096L17.66 18m0 0 .229 2.523a1.125 1.125 0 0 1-1.12 1.227H7.231c-.662 0-1.18-.568-1.12-1.227L6.34 18m11.318 0h1.091A2.25 2.25 0 0 0 21 15.75V9.456c0-1.081-.768-2.015-1.837-2.175a48.055 48.055 0 0 0-1.913-.247M6.34 18H5.25A2.25 2.25 0 0 1 3 15.75V9.456c0-1.081.768-2.015 1.837-2.175a48.041 48.041 0 0 1 1.913-.247m10.5 0a48.536 48.536 0 0 0-10.5 0m10.5 0V3.375c0-.621-.504-1.125-1.125-1.125h-8.25c-.621 0-1.125.504-1.125 1.125v3.659M18 10.5h.008v.008H18V10.5Zm-3 0h.008v.008H15V10.5Z',
  viewBox: 24,
  style: 'stroke',
  strokeWidth: 1.5
};

/** Heroicons `squares-2x2`, 24×24 outline. */
export const squares2x2: Glyph = {
  path:
    'M3.75 6A2.25 2.25 0 0 1 6 3.75h2.25A2.25 2.25 0 0 1 10.5 6v2.25a2.25 2.25 0 0 1-2.25 2.25H6a2.25 2.25 0 0 1-2.25-2.25V6ZM3.75 15.75A2.25 2.25 0 0 1 6 13.5h2.25a2.25 2.25 0 0 1 2.25 2.25V18a2.25 2.25 0 0 1-2.25 2.25H6A2.25 2.25 0 0 1 3.75 18v-2.25ZM13.5 6a2.25 2.25 0 0 1 2.25-2.25H18A2.25 2.25 0 0 1 20.25 6v2.25A2.25 2.25 0 0 1 18 10.5h-2.25a2.25 2.25 0 0 1-2.25-2.25V6ZM13.5 15.75a2.25 2.25 0 0 1 2.25-2.25H18a2.25 2.25 0 0 1 2.25 2.25V18A2.25 2.25 0 0 1 18 20.25h-2.25A2.25 2.25 0 0 1 13.5 18v-2.25Z',
  viewBox: 24,
  style: 'stroke',
  strokeWidth: 1.5
};

/** Heroicons `swatch`, 24×24 outline. */
export const swatch: Glyph = {
  path:
    'M4.098 19.902a3.75 3.75 0 0 0 5.304 0l6.401-6.402M6.75 21A3.75 3.75 0 0 1 3 17.25V4.125C3 3.504 3.504 3 4.125 3h5.25c.621 0 1.125.504 1.125 1.125v4.072M6.75 21a3.75 3.75 0 0 0 3.75-3.75V8.197M6.75 21h13.125c.621 0 1.125-.504 1.125-1.125v-5.25c0-.621-.504-1.125-1.125-1.125h-4.072M10.5 8.197l2.88-2.88c.438-.439 1.15-.439 1.59 0l3.712 3.713c.44.44.44 1.152 0 1.59l-2.879 2.88M6.75 17.25h.008v.008H6.75v-.008Z',
  viewBox: 24,
  style: 'stroke',
  strokeWidth: 1.5
};

/** Heroicons `table-cells`, 24×24 outline. */
export const tableCells: Glyph = {
  path:
    'M3.375 19.5h17.25m-17.25 0a1.125 1.125 0 0 1-1.125-1.125M3.375 19.5h7.5c.621 0 1.125-.504 1.125-1.125m-9.75 0V5.625m0 12.75v-1.5c0-.621.504-1.125 1.125-1.125m18.375 2.625V5.625m0 12.75c0 .621-.504 1.125-1.125 1.125m1.125-1.125v-1.5c0-.621-.504-1.125-1.125-1.125m0 3.75h-7.5A1.125 1.125 0 0 1 12 18.375m9.75-12.75c0-.621-.504-1.125-1.125-1.125H3.375c-.621 0-1.125.504-1.125 1.125m19.5 0v1.5c0 .621-.504 1.125-1.125 1.125M2.25 5.625v1.5c0 .621.504 1.125 1.125 1.125m0 0h17.25m-17.25 0h7.5c.621 0 1.125.504 1.125 1.125M3.375 8.25c-.621 0-1.125.504-1.125 1.125v1.5c0 .621.504 1.125 1.125 1.125m17.25-3.75h-7.5c-.621 0-1.125.504-1.125 1.125m8.625-1.125c.621 0 1.125.504 1.125 1.125v1.5c0 .621-.504 1.125-1.125 1.125m-17.25 0h7.5m-7.5 0c-.621 0-1.125.504-1.125 1.125v1.5c0 .621.504 1.125 1.125 1.125M12 10.875v-1.5m0 1.5c0 .621-.504 1.125-1.125 1.125M12 10.875c0 .621.504 1.125 1.125 1.125m-2.25 0c.621 0 1.125.504 1.125 1.125M13.125 12h7.5m-7.5 0c-.621 0-1.125.504-1.125 1.125M20.625 12c.621 0 1.125.504 1.125 1.125v1.5c0 .621-.504 1.125-1.125 1.125m-17.25 0h7.5M12 14.625v-1.5m0 1.5c0 .621-.504 1.125-1.125 1.125M12 14.625c0 .621.504 1.125 1.125 1.125m-2.25 0c.621 0 1.125.504 1.125 1.125m0 1.5v-1.5m0 0c0-.621.504-1.125 1.125-1.125m0 0h7.5',
  viewBox: 24,
  style: 'stroke',
  strokeWidth: 1.5
};

/** Heroicons `underline`, 24×24 outline. */
export const underline: Glyph = {
  path: 'M17.995 3.744v7.5a6 6 0 1 1-12 0v-7.5m-2.25 16.502h16.5',
  viewBox: 24,
  style: 'stroke',
  strokeWidth: 1.5
};
