import { serve, type ServedChannel } from 'gesso-framework';

import { Sheet } from './SheetContract';
import type { SheetService } from './SheetService';

/**
 * The channel, wired once.
 *
 * Every view key and every command in one place, so that the worker
 * and the four specs that mount a sheet cannot drift from each other.
 * They did: adding a command meant editing four literals, and the
 * compiler only said so because the token's type demanded all of them.
 */
export function sheetChannel(service: SheetService): ServedChannel {
  return serve(Sheet, {
    view: {
      window: service.window,
      sheets: service.sheets,
      validation: service.validation,
      geometry: service.geometry,
      selection: service.selection,
      editor: service.editor,
      names: service.names,
      status: service.status,
      clipboard: service.clipboard,
      transfer: service.transfer,
      document: service.documentView,
      stats: service.selectionStats,
      find: service.findView,
      formats: service.formats,
      palette: service.palette,
      activeFormat: service.activeFormat,
      activeRules: service.activeRules,
      autofit: service.autofit,
      completion: service.completion,
      notes: service.notes,
      rowFit: service.rowFit,
      charts: service.charts,
      series: service.chartSeries,
      scripts: service.scripts
    },
    commands: {
      setViewport: (sheet, firstRow, lastRow, firstColumn, lastColumn) =>
        service.setViewport(sheet, firstRow, lastRow, firstColumn, lastColumn),
      addConditional: rule => service.addConditional(rule),
      removeConditional: at => service.removeConditional(at),
      addValidation: (rule, strict, message) => service.addValidation(rule, strict, message),
      removeValidation: at => service.removeValidation(at),
      clearRules: () => service.clearRules(),
      importCsv: (fileName, text) => service.importCsv(fileName, text),
      exportCsv: () => service.exportCsv(),
      exportXlsx: () => service.exportXlsx(),
      openDocument: id => service.openDocument(id),
      openFile: (fileName, text, handle) => service.openFile(fileName, text, handle),
      importXlsx: (fileName, base64) => service.importXlsx(fileName, base64),
      saveDocument: asNew => service.saveDocument(asNew),
      fileSaved: (kind, name, handle, via) => service.fileSaved(kind, name, handle, via),
      reportFile: text => service.reportFile(text),
      insertChart: kind => service.insertChart(kind),
      selectChart: id => service.selectChart(id),
      placeChart: (id, x, y, width, height) => service.placeChart(id, x, y, width, height),
      setChartKind: (id, kind) => service.setChartKind(id, kind),
      setChartTitle: (id, title) => service.setChartTitle(id, title),
      setChartRange: (id, firstRow, firstColumn, lastRow, lastColumn) =>
        service.setChartRange(id, firstRow, firstColumn, lastRow, lastColumn),
      removeChart: id => service.removeChart(id),
      activateSheet: sheet => service.activateSheet(sheet),
      addSheet: () => service.addSheet(),
      renameSheet: (sheet, name) => service.renameSheet(sheet, name),
      removeSheet: sheet => service.removeSheet(sheet),
      moveSheet: (from, to) => service.moveSheet(from, to),
      duplicateSheet: sheet => service.duplicateSheet(sheet),
      setSheetColour: (sheet, colour) => service.setSheetColour(sheet, colour),
      setCell: (row, column, input) => service.setCell(row, column, input),
      setSelection: (row, column, anchorRow, anchorColumn, cornerRow, cornerColumn) =>
        service.setSelection(row, column, anchorRow, anchorColumn, cornerRow, cornerColumn),
      undo: () => service.undo(),
      redo: () => service.redo(),
      copy: cut => service.copy(cut),
      paste: (text, mode) => service.paste(text, mode),
      pasteSpecial: mode => service.pasteSpecial(mode),
      moveRange: (row, column, copy) => service.moveRange(row, column, copy),
      unmark: () => service.unmark(),
      pickFormats: () => service.pickFormats(),
      paintFormats: () => service.paintFormats(),
      clearRange: () => service.clearRange(),
      fill: (toRow, toColumn) => service.fill(toRow, toColumn),
      fillToData: () => service.fillToData(),
      jumpToEdge: (row, column, anchorRow, anchorColumn, rows, columns, extend) =>
        service.jumpToEdge(row, column, anchorRow, anchorColumn, rows, columns, extend),
      writeSelection: input => service.writeSelection(input),
      complete: (row, column, prefix, serial) => service.complete(row, column, prefix, serial),
      setNote: (row, column, text) => service.setNote(row, column, text),
      setColumnWidth: (column, width) => service.setColumnWidth(column, width),
      setRowHeight: (row, height) => service.setRowHeight(row, height),
      fitRowsToContents: (first, last) => service.fitRowsToContents(first, last),
      setIteration: on => service.setIteration(on),
      showFormulas: on => service.showFormulas(on),
      setZoom: zoom => service.setZoom(zoom),
      fitRows: (serial, heights) => service.fitRows(serial, heights),
      stress: cells => service.stress(cells),
      chartStress: points => service.chartStress(points),
      scriptStress: () => service.scriptStress(),
      functionStress: calls => service.functionStress(calls),
      fillDown: () => service.fillDown(),
      fillRight: () => service.fillRight(),
      find: (query, matchCase, wholeCell, inFormulas) => service.find(query, matchCase, wholeCell, inFormulas),
      findStep: forward => service.findStep(forward),
      replaceOne: replacement => service.replaceOne(replacement),
      replaceAll: replacement => service.replaceAll(replacement),
      clearFind: () => service.clearFind(),
      format: change => service.format(change),
      clearFormat: () => service.clearFormat(),
      insertRows: (at, count) => service.insertRows(at, count),
      deleteRows: (at, count) => service.deleteRows(at, count),
      insertColumns: (at, count) => service.insertColumns(at, count),
      deleteColumns: (at, count) => service.deleteColumns(at, count),
      setBorders: (pattern, width, color) => service.setBorders(pattern, width, color),
      sortRange: (column, ascending, hasHeader) => service.sortRange(column, ascending, hasHeader),
      hideColumns: (first, last) => service.hideColumns(first, last),
      showColumns: (first, last) => service.showColumns(first, last),
      hideRows: (first, last) => service.hideRows(first, last),
      showRows: (first, last) => service.showRows(first, last),
      freeze: (rows, columns) => service.freeze(rows, columns),
      mergeCells: () => service.mergeCells(),
      defineName: (name: string) => service.defineName(name),
      removeName: (name: string) => service.removeName(name),
      defineFormulaName: (name: string, formula: string) => service.defineFormulaName(name, formula),
      saveName: (was: string, name: string, refersTo: string) => service.saveName(was, name, refersTo),
      unmergeCells: () => service.unmergeCells(),
      measureColumns: (first, last) => service.measureColumns(first, last),
      filterToSelection: () => service.filterToSelection(),
      clearFilter: () => service.clearFilter(),
      saveScript: (was, name, source, kind) => service.saveScript(was, name, source, kind),
      removeScript: name => service.removeScript(name),
      runScript: (name, confirmed) => service.runScript(name, confirmed),
      stopScript: () => service.stopScript(),
      setFunctionsOn: on => service.setFunctionsOn(on)
    }
  });
}
